name: TermEnv


on:
  repository_dispatch:
  workflow_dispatch:

env:
  TZ: Asia/Shanghai

jobs:
  build_base:
    name: Build Term Env
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_HUB_USER_NAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    
      - name: Checkout batocera.linux
        uses: actions/checkout@v3
      - name: Checkout Buildroot
        uses: actions/checkout@v3
        with:
          repository: jurafish/buildroot
          path: buildroot
#      - name: Build ToolChain
#        run: |
#          set -xe
#          make s912-toolchain
        
      - name: Setup Debug Session
        uses: csexton/debugger-action@master
        
#      - name: Push image
#        run: docker push batoceralinux/batocera.linux-build
