name: TermEnv


on:
  repository_dispatch:
  workflow_dispatch:

env:
  TZ: Asia/Shanghai

jobs:
  build_base:
    name: Build Term Env
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_HUB_USER_NAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    
      - name: Checkout batocera.linux
        uses: actions/checkout@v3
      - name: Checkout Buildroot
        uses: actions/checkout@v3
        with:
          repository: jurafish/buildroot
          path: buildroot
      - name: Makedir DL
        run: |
          make dl-dir
          sudo chown -R runner:docker dl/
          #echo "hello download" >> dl/download.txt
          #sudo umount -l /tmp
          df > dl/df.txt
          sudo umount -l /mnt
          sudo mount /dev/sdb1 /tmp
          df > dl/df1.txt
          
      - name: Setup Debug Session
        uses: csexton/debugger-action@master
          
      - name: Build
        run:  make s912-build
  
      - name: Upload DL
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: dl-artifact
          path: |
            dl/
            output/
      - name: print diskinfo
        if: always()
        run: df > dl/df2.txt
        
#      - name: Push image
#        run: docker push batoceralinux/batocera.linux-build
