name: DownloadArtifact


on:
  repository_dispatch:
  workflow_dispatch:

env:
  TZ: Asia/Shanghai

jobs:
  build_base:
    name: Download Artifact
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        run: |
          echo "${{secrets.GITHUB_TOKEN}}"
          echo “------”
          #--header="Accept: application/vnd.github.v3+json" 
          #wget -O dl-artifact.zip --header="Authorization: token ${{secrets.GITHUB_TOKEN}}" https://api.github.com/repos/jurafish/batocera.linux/actions/artifacts/431535574/zip
      - name: Setup Debug Session
        uses: csexton/debugger-action@master
      - name: Setup Debug Session
        run: echo 'P3TERX/debugger-action@master'
