name: DownloadArtifact


on:
  repository_dispatch:
  workflow_dispatch:

env:
  TZ: Asia/Shanghai

jobs:
  build_base:
    name: Download Artifact
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        run: |
          echo "${{secrets.GITHUB_TOKEN}}"
          wget --no-check-certificate -O downloadArtifact.zip --header=PRIVATE-TOKEN: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 "https://github.com/jurafish/batocera.linux/suites/9232134721/artifacts/431535574"
      - name: Setup Debug Session
        uses: csexton/debugger-action@master
